.gitignore, Assets/Firebase.meta, Assets/Plugins.meta, Assets/Scripts/GameManager.cs, ProjectSettings/AndroidResolverDependencies.xml, ProjectSettings/GvhProjectSettings.xml, ProjectSettings/ProjectSettings.asset
* Android 빌드가 가능해짐
* Android 빌드시 Assets 폴더를 기준으로 고정된 경로를 참조하는 것으로 예상됨
=> Android Build 설정 및 해당 상황에서 Firebase 적용시 오류 해결

Assets/CJS.meta, Assets/CJS/UserDatabaseRnD.meta, Assets/CJS/UserDatabaseRnD/UserDataTest.unity, Assets/CJS/UserDatabaseRnD/UserDataTest.unity.meta, Assets/CJS/UserDatabaseRnD/UserDatabaseTester.cs, Assets/CJS/UserDatabaseRnD/UserDatabaseTester.cs.meta, Assets/Scripts/BackendManager.cs
* 시간으로 쌓이는 보상 수령 기능
* 출석 보상 기능
=> 시간이나 날짜를 통해 누적되는 보상 기능 R&D

Assets/Resources/DOTweenSettings.asset, Assets/Resources/DOTweenSettings.asset.meta, Assets/Test_Kmt.meta, Assets/Test_Kmt/Prefabs.meta, Assets/Test_Kmt/Prefabs/Character.prefab, Assets/Test_Kmt/Prefabs/Character.prefab.meta, Assets/Test_Kmt/Prefabs/Monster.prefab, Assets/Test_Kmt/Prefabs/Monster.prefab.meta, Assets/Test_Kmt/Scripts.meta, Assets/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/Test_Kmt/Scripts/CharacterCombatable.cs.meta, Assets/Test_Kmt/Scripts/CombManager.cs, Assets/Test_Kmt/Scripts/CombManager.cs.meta, Assets/Test_Kmt/Scripts/Combatable.cs, Assets/Test_Kmt/Scripts/Combatable.cs.meta, Assets/Test_Kmt/Scripts/Trackable.cs, Assets/Test_Kmt/Scripts/Trackable.cs.meta, Assets/Test_Kmt/TrackingTest.unity, Assets/Test_Kmt/TrackingTest.unity.meta, ProjectSettings/ProjectSettings.asset
사정거리에 따른 기본적인 적대 캐릭터 추적 로직과 공격 로직 작성
=> [feat] : tracking and basic combat system

Assets/YSC/01Scripts/UI_Manager.cs
=> YSC -> Dev 버그픽스

Assets/_WorkSpace/Datas/StoryDirectings.meta, Assets/_WorkSpace/Datas/StoryDirectings/StoryDataSample.asset, Assets/_WorkSpace/Datas/StoryDirectings/StoryDataSample.asset.meta, Assets/_WorkSpace/Resources/Data Manager.asset, Assets/_WorkSpace/Resources/GameManager.prefab, Assets/_WorkSpace/Scripts/CharacterData.cs, Assets/_WorkSpace/Scripts/DataManager.cs, Assets/_WorkSpace/Scripts/StoryDirectingData.cs, Assets/_WorkSpace/Scripts/StoryDirectingData.cs.meta
* DataManager.GetSheetDataFromSheet<T>() 메서드
* StoryDirectingData 클래스
=> 시트 기반 스토리 연출 데이터 구조 설계 및 파싱 기능

Assets/Test_Kmt/Scripts/CombManager.cs, Assets/Test_Kmt/Scripts/Combatable.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scene/SkillDevScene_kmt.unity, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageCharacterSetter.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/Scripts/Actions/SingleTargetDamage.cs, Assets/_WorkSpace/Scripts/Actions/Skill.cs, Assets/_WorkSpace/Scripts/Actions/TargetDeadlyPercentageAlly.cs, Assets/_WorkSpace/Scripts/Actions/TargetNearEnemy.cs, Assets/_WorkSpace/Scripts/Actions/Targeting.cs
* Assets/_WorkSpace/KMT/02_SkillSystem/Scene/SkillDevScene_kmt.unity 씬에 구현
=> [Refactor]: 캐릭터가 외부로부터 주입된 스킬을 사용

Assets/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/Test_Kmt/Scripts/CombManager.cs, Assets/Test_Kmt/Scripts/Combatable.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Prefabs/WaveController.prefab, Assets/_WorkSpace/KMT/02_SkillSystem/Prefabs/WaveController.prefab.meta, Assets/_WorkSpace/KMT/02_SkillSystem/Scene/SkillDevScene_kmt.unity, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/MonsterWaveSetter.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/MonsterWaveSetter.cs.meta, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageCharacterSetter.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/WavesParent.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/WavesParent.cs.meta
전달받은 정보를 기반으로 몬스터 웨이브 생성, 전투 흐름 진행 개발
=> [feat] : monster wave sys

Assets/_WorkSpace/YSC/01Scripts/EmailAuth.cs, Assets/_WorkSpace/YSC/01Scripts/SignUpPanel.cs
=> YSC -> Dev [Fix]: 경고문 나오는 코드 수정

Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs
=> [fix] : fix state coroutine

Assets/Resources/DOTweenSettings.asset, Assets/_WorkSpace/Datas/Skills/SampleSkill.asset, Assets/_WorkSpace/KMT/02_SkillSystem/Prefabs/SkillButton.prefab, Assets/_WorkSpace/KMT/02_SkillSystem/Scene/SkillDevScene_kmt.unity, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/SkillButton.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/SkillButton.cs.meta, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageCharacterSetter.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs
=> [feat] : skill cooldown

Assets/Resources/DOTweenSettings.asset, Assets/_WorkSpace/CJS/UILayoutTest.meta, Assets/_WorkSpace/CJS/UILayoutTest/UILayaoutTestScene.unity, Assets/_WorkSpace/CJS/UILayoutTest/UILayaoutTestScene.unity.meta, Assets/_WorkSpace/Prefabs/UI Canvas/Horizontal Axis Canvas.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/Horizontal Axis Canvas.prefab.meta, Assets/_WorkSpace/Prefabs/UI Canvas/Vertical Axis Canvas.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/Vertical Axis Canvas.prefab.meta, Assets/_WorkSpace/SHW/Scripts/Done/SafeArea.cs
UI를 좌우로 붙일지, 상하로 붙일지에 따라 다른 프리팹 사용
=> 화면비 대응 캔버스

Assets/_WorkSpace/CJS/UserDatabaseRnD/UserDatabaseTester.cs, Assets/_WorkSpace/Datas/Character/FormationTest1.asset, Assets/_WorkSpace/Datas/Character/FormationTest2.asset, Assets/_WorkSpace/Datas/Character/FormationTest3.asset, Assets/_WorkSpace/Datas/Character/FormationTest4.asset, Assets/_WorkSpace/Datas/Character/FormationTest5.asset, Assets/_WorkSpace/Datas/Character/fileNameeee.asset, Assets/_WorkSpace/Datas/Character/test1ho.asset, Assets/_WorkSpace/Scripts/CharacterData.cs, Assets/_WorkSpace/Scripts/DataManager.cs, ProjectSettings/EditorSettings.asset
DB 변경 요청 전송 예시
```
GameManager.Data.StartUpdateStream()
.SetDBValue(characterData.Level, characterData.Level.Value + 1)
.SetDBValue(gold, gold.Value - 1000)
.Submit(result =>
{
if (false == result)
{
Debug.LogWarning("갱신 실패");
return;
}
Debug.Log("갱신 성공");
});
```
=> [Feat]: DB 연동 유저 데이터용 프로퍼티 생성

Assets/_WorkSpace/BSM/Scene/CharacterInfoScene.unity, Assets/_WorkSpace/BSM/Scripts/CharacterInfo/CharacterInfo.cs, Assets/_WorkSpace/BSM/Scripts/CharacterInfo/CharacterInfoController.cs, Assets/_WorkSpace/CJS/UserDatabaseRnD/UserDatabaseTester.cs, Assets/_WorkSpace/Resources/Data Manager.asset, Assets/_WorkSpace/Scripts/DataManager.cs
캐릭터 정보창에서 레벨업 요청 전송 및 실제 적용 확인
=> 데이터베이스 갱신 요청 실사용

Assets/_WorkSpace/KMT/04_RankSystem.meta, Assets/_WorkSpace/KMT/04_RankSystem/Prefabs.meta, Assets/_WorkSpace/KMT/04_RankSystem/Prefabs/RankBlock.prefab, Assets/_WorkSpace/KMT/04_RankSystem/Prefabs/RankBlock.prefab.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scene.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scene/RankScene_kmt.unity, Assets/_WorkSpace/KMT/04_RankSystem/Scene/RankScene_kmt.unity.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scripts.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankApplier.cs, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankApplier.cs.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankBlock.cs, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankBlock.cs.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankingBoard.cs, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankingBoard.cs.meta, ProjectSettings/EditorSettings.asset
=> [feat] : ranking board system

Assets/_WorkSpace/KMT/03_DialogueSystem/Scripts/OpenableUIBase.cs, Assets/_WorkSpace/KMT/06_MenuChangeSystem.meta, Assets/_WorkSpace/KMT/06_MenuChangeSystem/Scenes.meta, Assets/_WorkSpace/KMT/06_MenuChangeSystem/Scenes/ViewChange.unity, Assets/_WorkSpace/KMT/06_MenuChangeSystem/Scenes/ViewChange.unity.meta, Assets/_WorkSpace/KMT/06_MenuChangeSystem/Scripts.meta, Assets/_WorkSpace/KMT/06_MenuChangeSystem/Scripts/ViewManager.cs, Assets/_WorkSpace/KMT/06_MenuChangeSystem/Scripts/ViewManager.cs.meta
=> [feat] : inner scene change system

Assets/_WorkSpace/CJS/CurrencyItemUI.cs, Assets/_WorkSpace/CJS/CurrencyItemUI.cs.meta, Assets/_WorkSpace/CJS/UserDatabaseRnD/UserDataTest.unity, Assets/_WorkSpace/Prefabs/UI Canvas/CurrencyItemUI.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/CurrencyItemUI.prefab.meta
레이아웃은 각 UI 창의 요구사항에 맞춰 조정해서 써 주세요~
=> [Feat]: 아이템(재화) 아이콘과 소지 개수를 출력하는 프리팹

Assets/_WorkSpace/Datas/Character/01_test1ho.asset, Assets/_WorkSpace/Datas/Character/01_test1ho.asset.meta, Assets/_WorkSpace/Datas/Character/02_fileNameeee.asset, Assets/_WorkSpace/Datas/Character/02_fileNameeee.asset.meta, Assets/_WorkSpace/Datas/Character/03_FormationTest1.asset, Assets/_WorkSpace/Datas/Character/03_FormationTest1.asset.meta, Assets/_WorkSpace/Datas/Character/04_FormationTest2.asset, Assets/_WorkSpace/Datas/Character/04_FormationTest2.asset.meta, Assets/_WorkSpace/Datas/Character/05_FormationTest3.asset, Assets/_WorkSpace/Datas/Character/05_FormationTest3.asset.meta, Assets/_WorkSpace/Datas/Character/06_FormationTest4.asset, Assets/_WorkSpace/Datas/Character/06_FormationTest4.asset.meta, Assets/_WorkSpace/Datas/Character/07_FormationTest5.asset, Assets/_WorkSpace/Datas/Character/07_FormationTest5.asset.meta, Assets/_WorkSpace/Resources/Data Table Manager.asset, Assets/_WorkSpace/Scripts/CharacterData.cs, Assets/_WorkSpace/Scripts/DataTableManager.cs, Assets/_WorkSpace/Scripts/UserDataManager.cs, Assets/_WorkSpace/YSC/01Scripts/ShopItem.cs
=> [Feat]: 캐릭터 능력치 데이터 열 추가

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/KMT/05_SecondSkillSystem/Scene/SecondSkillSystem_kmt.unity, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CombManager.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs
=> [feat] : apply status in combat

Assets/_WorkSpace/KMT/02_SkillSystem/Prefabs/SecondSkillButton.prefab, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/MonsterWaveSetter.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/SecondSkillButton.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/KMT/05_SecondSkillSystem/Scene/SecondSkillSystem_kmt.unity, Assets/_WorkSpace/KMT/07_CostDisplay.meta, Assets/_WorkSpace/KMT/07_CostDisplay/Scenes.meta, Assets/_WorkSpace/Prefabs/SampleUnit2.prefab, Assets/_WorkSpace/Prefabs/SampleUnit3.prefab, Assets/_WorkSpace/Prefabs/SampleUnit4.prefab
비용 디스플레이 슬라이더 추가 + 적 처치시 코스트 획득 기능 추가
=> [feat] : cost displayer + gain kill cost

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/BasicSkillButton.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/SecondSkillButton.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageCharacterSetter.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs
=> [feat] : disable skill button

Assets/_WorkSpace/Prefabs/UI Canvas/MyRoom.prefab, Assets/_WorkSpace/SHW/Scene/UITestScene.unity, Assets/_WorkSpace/SHW/Scripts/EggSpawner.cs, Assets/_WorkSpace/SHW/Scripts/EggSpawner.cs.meta, Assets/_WorkSpace/SHW/Scripts/MyRoomUI.cs
- 용 부화기 기능 (DB 연결 필요)
- 마이룸 패널 오류 수정
- 마이룸 UI 수정(추가 작업 필요)(미완료)
=> [feat] 용 부화기 기능 및 일부기능 수정

Assets/_WorkSpace/KMT/08_Projectile/Scripts/Projectile.cs, Assets/_WorkSpace/KMT/09_DamageCalc.meta, Assets/_WorkSpace/KMT/09_DamageCalc/Scenes.meta, Assets/_WorkSpace/KMT/09_DamageCalc/Scenes/DamageCalc_kmt.unity, Assets/_WorkSpace/KMT/09_DamageCalc/Scenes/DamageCalc_kmt.unity.meta, Assets/_WorkSpace/KMT/09_DamageCalc/Scripts.meta, Assets/_WorkSpace/KMT/09_DamageCalc/Scripts/DamageCalculator.cs, Assets/_WorkSpace/KMT/09_DamageCalc/Scripts/DamageCalculator.cs.meta, Assets/_WorkSpace/KMT/Test_Kmt/Prefabs/Character.prefab, Assets/_WorkSpace/KMT/Test_Kmt/Prefabs/Monster.prefab, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs, Assets/_WorkSpace/Scripts/Actions/BasicAttack.cs, Assets/_WorkSpace/Scripts/Actions/BasicRangeAttack.cs, Assets/_WorkSpace/Scripts/Actions/SingleTargetDamage.cs
=> [feat] : hpSlider, damageCalc

Assets/_WorkSpace/CJS/UserDatabaseRnD/UserDatabaseTester.cs, Assets/_WorkSpace/SHW/Scene/UITestScene.unity, Assets/_WorkSpace/SHW/Scripts/EggSpawner.cs, Assets/_WorkSpace/Scripts/UserDataManager.cs, ProjectSettings/EditorSettings.asset
서버 타임스탬프 값을 곧바로 가져올 수 없기 때문에 유저 데이터에 입력+읽어오기 2단계를 거치게 되었습니다
=> 유저 데이터에 서버 시간 기반 타임스탬프 입력  기능 및 알 부화기에 적용

Assets/_WorkSpace/KMT/11_GetCharacter.meta, Assets/_WorkSpace/KMT/11_GetCharacter/Scenes.meta, Assets/_WorkSpace/KMT/11_GetCharacter/Scenes/GainCharacter.unity, Assets/_WorkSpace/KMT/11_GetCharacter/Scenes/GainCharacter.unity.meta, Assets/_WorkSpace/KMT/11_GetCharacter/Scripts.meta, Assets/_WorkSpace/KMT/11_GetCharacter/Scripts/CharacterApplier.cs, Assets/_WorkSpace/KMT/11_GetCharacter/Scripts/CharacterApplier.cs.meta, Assets/_WorkSpace/KMT/11_GetCharacter/Scripts/GainTester.cs, Assets/_WorkSpace/KMT/11_GetCharacter/Scripts/GainTester.cs.meta, Assets/_WorkSpace/Scripts/UserDataManager.cs, ProjectSettings/EditorSettings.asset
=> [feat] : gain character

Assets/_WorkSpace/Datas/Stages/01_Stage1-1.asset, Assets/_WorkSpace/Datas/StoryDirectings/StoryDataSample.asset, Assets/_WorkSpace/Scripts/StoryDirectingData.cs
대사를 큰 따옴표로 감싸기 위해서는 전체 대사를 `| (shift + \)`로 감싸야 합니다
=> [Fix]: 대사에 줄바꿈과 큰 따옴표 사용 가능

Assets/_WorkSpace/KMT/03_DialogueSystem/Scenes/DialogueScene_kmt.unity, Assets/_WorkSpace/KMT/03_DialogueSystem/Scenes/WaitFirebaseScene.unity, Assets/_WorkSpace/KMT/03_DialogueSystem/Scripts/BeforeSceneScript.cs, Assets/_WorkSpace/KMT/03_DialogueSystem/Scripts/DialogueUI.cs, ProjectSettings/EditorBuildSettings.asset
dummyX라는 uid기반 채팅 동작 테스트.
추후 초기화 타이밍 조정 필요
=> [chore] : apply nickname

Assets/_WorkSpace/KMT/01_FriendSystem/Scripts/UserData.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/BasicSkillButton.cs, Assets/_WorkSpace/KMT/10_BossCombat/Scripts/BossStageManager.cs, Assets/_WorkSpace/KMT/10_BossCombat/Scripts/SceneChanger.cs, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scenes/BossCombat_Cheatkey.unity, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scenes/CoinDungeon_Cheatkey.unity, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scenes/Combat_Cheatkey.unity, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scenes/ReadyScene.unity, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scripts/SkillCooldownCheat.cs, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scripts/SkillCooldownCheat.cs.meta, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs, Assets/_WorkSpace/Scenes/MainMenu.unity, Assets/_WorkSpace/Scenes/StageDefault.unity, Assets/_WorkSpace/Scenes/StageDefault.unity.meta
=> [feat] : cooldown cheatkey

Assets/_WorkSpace/HYJ_Test/Prefabs/CharacterBTN.prefab, Assets/_WorkSpace/HYJ_Test/Prefabs/CharacterBTN.prefab.meta, Assets/_WorkSpace/HYJ_Test/Scenes/HYJ_BattleFormation.unity, Assets/_WorkSpace/HYJ_Test/Scenes/HYJ_BattleFormation.unity.meta, Assets/_WorkSpace/HYJ_Test/Scenes/HYJ_BattleReady.unity, Assets/_WorkSpace/HYJ_Test/Scripts/HYJ_CharacterSelect.cs, Assets/_WorkSpace/HYJ_Test/Scripts/HYJ_SelectManager.cs
-기획서의 변경점을 반영한 UI 제작 및 배치, 설정 중
-추가로 필요한 기능 생성(캐릭터 정보 보여주기)
=> Feat : 새로운 전투 배치 툴 제작

Assets/_WorkSpace/Prefabs/UI Canvas/MyRoom.prefab, Assets/_WorkSpace/SHW/Prefabs/UserProfile.prefab, Assets/_WorkSpace/SHW/Scripts/UserProfileUI.cs
=> Feat/shw : 플레이어 정보 ui 배치사항 수정

Assets/_WorkSpace/KMT/01_FriendSystem/FriendList/Prefabs/FriendBlock.prefab, Assets/_WorkSpace/KMT/01_FriendSystem/FriendList/Scripts/FriendBlock.cs, Assets/_WorkSpace/KMT/01_FriendSystem/FriendList/Scripts/FriendList.cs, Assets/_WorkSpace/KMT/01_FriendSystem/Scripts/FriendBaseUI.cs, Assets/_WorkSpace/KMT/01_FriendSystem/Scripts/MyRoomOpenable.cs, Assets/_WorkSpace/KMT/01_FriendSystem/Scripts/MyRoomOpenable.cs.meta, Assets/_WorkSpace/KMT/03_DialogueSystem/Scripts/DialogueUI.cs, Assets/_WorkSpace/KMT/15_MyRoomCustom/Scripts/MyroomInitializer.cs, Assets/_WorkSpace/KMT/16_OpenablePadderUI/Scripts/FocusableTab.cs, Assets/_WorkSpace/SHW/Scripts/MyRoomUI.cs, Assets/_WorkSpace/Scenes/LoginSelection.unity, Assets/_WorkSpace/Scenes/MainMenu.unity, Assets/_WorkSpace/Scripts/CanvasSwitch.cs, Assets/_WorkSpace/Scripts/OpenableUIBase.cs
=> [feat] : myroom system

Assets/_WorkSpace/Datas/Character/01_test1ho.asset, Assets/_WorkSpace/Datas/Character/02_fileNameeee.asset, Assets/_WorkSpace/Datas/Character/03_FormationTest1.asset, Assets/_WorkSpace/Datas/Character/04_FormationTest2.asset, Assets/_WorkSpace/Datas/Character/05_FormationTest3.asset, Assets/_WorkSpace/Datas/Items/Tocken_Enhance.asset, Assets/_WorkSpace/Datas/Items/Tocken_Enhance.asset.meta, Assets/_WorkSpace/Datas/Items/Tocken_LvUp.asset, Assets/_WorkSpace/Datas/Items/Tocken_LvUp.asset.meta, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/RankApplier.cs, Assets/_WorkSpace/KMT/10_BossCombat/Scripts/BossStageManager.cs, Assets/_WorkSpace/KMT/12_GoldDungeon/Scripts/GoldStageManager.cs, Assets/_WorkSpace/Prefabs/UI Canvas/Character.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/ItemGainPopup Void Variant.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/ItemGainPopup Void Variant.prefab.meta, Assets/_WorkSpace/Prefabs/UI Canvas/StoryDirector.prefab, Assets/_WorkSpace/Resources/Data Table Manager.asset, Assets/_WorkSpace/SHW/Scripts/EggSpawner.cs, Assets/_WorkSpace/Scenes/Stage_Boss.unity, Assets/_WorkSpace/Scenes/Stage_Coin.unity
* 대사창 터치시 대사 넘어가지 않는 버그 픽스
* 다른 창을 갔다오면 알 부화기 타이머가 멈추는 버그 픽스
* 특수 스테이지에 클리어 오버레이UI 추가
=> 잔버그 픽스 및 특수 스테이지에 클리어 오버레이UI 추가

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/MonsterWaveSetter.cs, Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageCharacterSetter.cs, Assets/_WorkSpace/KMT/10_BossCombat/Prefabs/BossMonster.prefab, Assets/_WorkSpace/KMT/Test_Kmt/Prefabs/Character.prefab, Assets/_WorkSpace/KMT/Test_Kmt/Prefabs/Monster.prefab, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs
=> [fix] : remove characters background icon

Assets/_WorkSpace/KMT/04_RankSystem/Scripts/OpenableRankPanel.cs, Assets/_WorkSpace/KMT/04_RankSystem/Scripts/OpenableRankPanel.cs.meta, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scripts/CharacterImmune.cs, Assets/_WorkSpace/KMT/18_MyRanking.meta, Assets/_WorkSpace/KMT/18_MyRanking/Scripts.meta, Assets/_WorkSpace/KMT/18_MyRanking/Scripts/MyRankSetter.cs, Assets/_WorkSpace/KMT/18_MyRanking/Scripts/MyRankSetter.cs.meta, Assets/_WorkSpace/Scenes/MainMenu.unity
=> [feat] : own ranking block

Assets/_WorkSpace/CJS/AdventureUI.prefab, Assets/_WorkSpace/CJS/Stage Button.prefab, Assets/_WorkSpace/Datas/Character/01_test1ho.asset, Assets/_WorkSpace/Datas/Character/03_FormationTest1.asset, Assets/_WorkSpace/Datas/Character/M_002_Chick.asset, Assets/_WorkSpace/Datas/Character/M_002_Chick.asset.meta, Assets/_WorkSpace/Datas/Character/M_003_Chicken.asset, Assets/_WorkSpace/Datas/Character/M_003_Chicken.asset.meta, Assets/_WorkSpace/Datas/Items/CT_02_fileNameeee.asset, Assets/_WorkSpace/Datas/Items/CT_02_fileNameeee.asset.meta, Assets/_WorkSpace/Datas/Items/CT_03_FormationTest1.asset, Assets/_WorkSpace/Datas/Items/CT_03_FormationTest1.asset.meta, Assets/_WorkSpace/Datas/Items/GC_02_fileNameeee.asset, Assets/_WorkSpace/Datas/Items/GC_02_fileNameeee.asset.meta, Assets/_WorkSpace/Datas/Items/GC_03_FormationTest1.asset, Assets/_WorkSpace/Datas/Items/GC_03_FormationTest1.asset.meta, Assets/_WorkSpace/Datas/Stages/01_Stage1-1.asset, Assets/_WorkSpace/Datas/Stages/03_Stage1-3.asset, Assets/_WorkSpace/Datas/Stages/03_Stage1-3.asset.meta, Assets/_WorkSpace/Datas/StoryDirectings/01_StoryDataSample.asset, Assets/_WorkSpace/Datas/StoryDirectings/02_MultiSheetTest.asset, Assets/_WorkSpace/Prefabs/Chick.prefab, Assets/_WorkSpace/Prefabs/Chick.prefab.meta, Assets/_WorkSpace/Prefabs/Chicken.prefab, Assets/_WorkSpace/Prefabs/Chicken.prefab.meta, Assets/_WorkSpace/Resources/Data Table Manager.asset, Assets/_WorkSpace/Scenes/MainMenu.unity, Assets/_WorkSpace/Scripts/StageData.cs
캐릭터 획득 아이템 2종
닭 몬스터 2종
스테이지 1종 추가
=> [Feat]: 캐릭터 획득 시연용 스테이지 추가

Assets/_WorkSpace/KMT/17_StageTypeSelecter/Scripts/EnterStageButton.cs, Assets/_WorkSpace/KMT/17_StageTypeSelecter/Scripts/GoldStageEnterButton.cs, Assets/_WorkSpace/KMT/17_StageTypeSelecter/Scripts/GoldStageEnterButton.cs.meta, Assets/_WorkSpace/Scenes/MainMenu.unity
=> [fix] : enter boss condition

Assets/_WorkSpace/HYJ_Test/Scenes/HYJ_BattleFormation.unity, Assets/_WorkSpace/HYJ_Test/Scripts/HYJ_CharacterSelect.cs, Assets/_WorkSpace/HYJ_Test/Scripts/HYJ_SelectManager.cs
=> Fix : 기획 반영사항 추가

Assets/_WorkSpace/SHW/Prefabs/UserProfile.prefab, Assets/_WorkSpace/SHW/Scripts/SetUserIcon.cs, Assets/_WorkSpace/SHW/Scripts/SetUserIcon.cs.meta, Assets/_WorkSpace/SHW/Scripts/UserProfileUI.cs
=> [feat] 유저 아이콘 변경

Assets/_WorkSpace/Datas/ShopItems/GoldToSlimeSample.asset, Assets/_WorkSpace/YSC/01Scripts/PurchasingPanel.cs
=> Build/item gain display => Develop

Assets/_WorkSpace/BSM/Scripts/Enum.cs, Assets/_WorkSpace/CJS/StartGameScene.cs, Assets/_WorkSpace/Datas/Character/01_test1ho.asset, Assets/_WorkSpace/Datas/Character/02_fileNameeee.asset, Assets/_WorkSpace/Datas/Character/03_FormationTest1.asset, Assets/_WorkSpace/Datas/Character/04_FormationTest2.asset, Assets/_WorkSpace/Datas/Character/05_FormationTest3.asset, Assets/_WorkSpace/Datas/Character/06_FormationTest4.asset, Assets/_WorkSpace/Datas/Character/07_FormationTest5.asset, Assets/_WorkSpace/Datas/Character/08_SortTest1.asset, Assets/_WorkSpace/Datas/Character/09_SortTest2.asset, Assets/_WorkSpace/Datas/Character/10_SortTest3.asset, Assets/_WorkSpace/Datas/Character/11_SortTest4.asset, Assets/_WorkSpace/Datas/Character/12_SortTest5.asset, Assets/_WorkSpace/Datas/Character/13_SortTest6.asset, Assets/_WorkSpace/Datas/Character/14_SortTest7.asset, Assets/_WorkSpace/Datas/Character/15_SortTest8.asset, Assets/_WorkSpace/Datas/Character/16_DummyBoss.asset, Assets/_WorkSpace/Datas/Character/17_DummyMimic.asset, Assets/_WorkSpace/Datas/Character/M_001_ParseLineTest.asset, Assets/_WorkSpace/Datas/Character/M_002_Chick.asset, Assets/_WorkSpace/Datas/Character/M_003_Chicken.asset, Assets/_WorkSpace/Prefabs/UI Canvas/Outskirts UI.prefab, Assets/_WorkSpace/Scripts/CharacterData.cs
드롭 다운으로 속성 선택
무속성 추가
중복 정의된 enum 정리
=> [Feat]: 캐릭터 데이터 시트에 유틸 추가 및 enum 순서 조정

Assets/_WorkSpace/CJS/CameraRnD/Camera Stacking RnD.unity, Assets/_WorkSpace/CJS/Chapter Button.prefab, Assets/_WorkSpace/CJS/Episode Button.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/StoryDirector.prefab, Assets/_WorkSpace/Scenes/StoryMenuScene.unity, Assets/_WorkSpace/Scripts/GameManager.cs, Assets/_WorkSpace/Scripts/StoryDirector.cs, Assets/_WorkSpace/Scripts/StoryEpisodeData.cs, Assets/_WorkSpace/Scripts/StoryEpisodeData.cs.meta
* 카메라 스태킹으로 스토리 재생
* 각 에피소드에 필요할 데이터 정리
=> 스토리 재생 후 전투 진입 씬 플로우를 위한 준비 작업

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/Scripts/StageData.cs
따로 설정하지 않으면 자신의 `ID - 1`이 선행 스테이지 입니다
해당 번호가 비어있다면 잠기지 않습니다
=> [Feat[: 스테이지 진입 조건(잠김) 구현

Assets/_WorkSpace/CJS/AdventureUI.cs, Assets/_WorkSpace/CJS/StagePanel.cs, Assets/_WorkSpace/CJS/StageTester.cs, Assets/_WorkSpace/CJS/StageTester.cs.meta, Assets/_WorkSpace/Scenes/AdvantureMenuScene.unity, Assets/_WorkSpace/Scripts/DataTableManager.cs
* 모든 스테이지 데이터를 가져와 강제로 개방
* 스토리, 보스 등 특수 스테이지로 진입시 정상 작동을 보장하지 않음
=> [Feat]: 스테이지 데이터 테스트용 기능

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/KMT/10_BossCombat/Scripts/BossStageManager.cs, Assets/_WorkSpace/KMT/12_GoldDungeon/Scripts/GoldStageManager.cs, Assets/_WorkSpace/KMT/23_CombatSystemExpand/Prefabs/UILayoutCanvas.prefab, Assets/_WorkSpace/KMT/28_AdvendedItemGainPopup/Scripts/AdvencedPopupInCombatResult.cs, Assets/_WorkSpace/KMT/28_AdvendedItemGainPopup/Scripts/AdvencedPopupInCombatResult.cs.meta, Assets/_WorkSpace/Scenes/StageDefault.unity, Assets/_WorkSpace/Scenes/Stage_Boss.unity, Assets/_WorkSpace/Scenes/Stage_Coin.unity, Assets/_WorkSpace/Scenes/Stage_Story.unity, Assets/_WorkSpace/Scripts/ItemGainPopup.cs, Assets/_WorkSpace/YSC/02Prefabs/itemTest/Itme Gain Cell.prefab, ProjectSettings/EditorSettings.asset
전투 종료 창 레이아웃 구성
TODO : 다음 스테이지 조건 추가, 보스 스테이지 결과 레이아웃 재구성
=> [feat] : combat result layout

Assets/_WorkSpace/BSM/Scripts/Enum.cs, Assets/_WorkSpace/KMT/08_Projectile/Scripts/Projectile.cs, Assets/_WorkSpace/KMT/09_DamageCalc/Scripts/DamageCalculator.cs, Assets/_WorkSpace/KMT/14_CombatCheatkey/Scripts/WaveClearCheat.cs, Assets/_WorkSpace/KMT/29_ElementalDamageSys.meta, Assets/_WorkSpace/KMT/29_ElementalDamageSys/Scripts.meta, Assets/_WorkSpace/KMT/29_ElementalDamageSys/Scripts/ElementalDamageGrid.cs, Assets/_WorkSpace/KMT/29_ElementalDamageSys/Scripts/ElementalDamageGrid.cs.meta, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs, Assets/_WorkSpace/Scripts/Actions/Skills/BasicSkill/BasicAttack.cs, Assets/_WorkSpace/Scripts/Actions/Skills/BasicSkill/BasicRangeAttack.cs, Assets/_WorkSpace/Scripts/Actions/Skills/CostCooltimeSkill/SingleTargetDamage.cs
=> [feat] : element Damage System

Assets/_WorkSpace/CJS/StoryActor.cs, Assets/_WorkSpace/CJS/StoryActor.cs.meta, Assets/_WorkSpace/Datas/StoryDirectings/01_StoryDataSample.asset, Assets/_WorkSpace/Datas/StoryDirectings/02_MultiSheetTest.asset, Assets/_WorkSpace/Datas/StoryDirectings/StoryScript_10810010001.asset, Assets/_WorkSpace/Datas/StoryDirectings/StoryScript_10810010001.asset.meta, Assets/_WorkSpace/Prefabs/UI Canvas/StoryActor.prefab, Assets/_WorkSpace/Prefabs/UI Canvas/StoryDirector.prefab, Assets/_WorkSpace/Scripts/StoryDirectingData.cs, Assets/_WorkSpace/Scripts/StoryDirector.cs
=> 스토리 트랜지션 연출 샘플 추가

Assets/_WorkSpace/KMT/23_CombatSystemExpand/Prefabs/UILayoutCanvas Variant.prefab, Assets/_WorkSpace/KMT/23_CombatSystemExpand/Prefabs/UILayoutCanvas.prefab, Assets/_WorkSpace/Scenes/StageDefault.unity, Assets/_WorkSpace/Scenes/Stage_Boss.unity, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/EditorSettings.asset
전투장면 기기에따른 safearea 비율에 맞춰 UI 배치
=> [feat] : stageScene safe area

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/LevelupButton.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/Scenes/AdvantureMenuScene.unity
=> [feat] : levelup cooldown

Assets/_WorkSpace/KMT/25_CombatOthers/RightTopButtons/Scripts/PauseWindow.cs, Assets/_WorkSpace/KMT/27_DungeonMenu/Scripts/GoldDungeonManage.cs, Assets/_WorkSpace/KMT/31_SkipAnimation.meta, Assets/_WorkSpace/KMT/31_SkipAnimation/Prefabs.meta, Assets/_WorkSpace/KMT/31_SkipAnimation/Prefabs/LoadingImgPanel.prefab, Assets/_WorkSpace/KMT/31_SkipAnimation/Prefabs/LoadingImgPanel.prefab.meta, Assets/_WorkSpace/KMT/31_SkipAnimation/Scripts.meta, Assets/_WorkSpace/KMT/31_SkipAnimation/Scripts/SkipAnimationWindow.cs, Assets/_WorkSpace/KMT/31_SkipAnimation/Scripts/SkipAnimationWindow.cs.meta, Assets/_WorkSpace/KMT/31_SkipAnimation/Texture.meta, Assets/_WorkSpace/Scenes/AdvantureMenuScene.unity, Assets/_WorkSpace/Scripts/GameManager.cs, ProjectSettings/EditorSettings.asset
=> [feat] : dungeon skip effect

Assets/_WorkSpace/KMT/03_DialogueSystem/Scripts/DialogueUI.cs, Assets/_WorkSpace/SHW/Scripts/MyRoomScripts/MyRoomUI.cs, Assets/_WorkSpace/Scenes/MyRoomScene.unity
* 내방에서 채팅창이 제대로 열리지 않던 버그 수정
* 내방으로 돌아가기 버튼 사용시 도감버튼 활성화 되던 부분 수정
=> [Fix]: 마이룸 채팅창, 돌아가기 버튼 버그 수정

Assets/_WorkSpace/KMT/02_SkillSystem/Scripts/StageManager.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CharacterCombatable.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/CombManager.cs, Assets/_WorkSpace/KMT/Test_Kmt/Scripts/Combatable.cs
=> [feat] : combat animation
